### GET Product request
GET http://localhost:3000/products HTTP/1.1
### POST Product request
POST http://localhost:3000/products HTTP/1.1
Content-Type: application/json

{
  "Name": "Yuki",
  "Description": "a dog",
  "Price": 1,
  "SKU": "adad-adasd-asda"
}
### PUT Product request
PUT http://localhost:3000/products HTTP/1.1
Content-Type: application/json

{
  "ID": 1,
  "Name": "Maki",
  "Description": "a cat",
  "Price": 2,
  "SKU": "adad-adasd-asda"
}
### DELETE Product request
DELETE http://localhost:3000/ HTTP/1.1